@startuml

' Client to Infrastructure
ClientBrowser -- StaticContent : https
ClientBrowser -- DNS : dns
ClientBrowser -- Proxy : https
ClientBrowser -- FirebaseAuth : https
ClientBrowser -- Stripe : https
Proxy -- Firewall : https
' Infrastructure comunications
Firewall -- LoadBalancer : https
LoadBalancer -- RestAPI : https
LoadBalancer -- WebServer : https
' TODO: Don't really know about this???
RestAPI -- Database : tcp
' Infrastructure to external
RestAPI -- FirebaseAuth : https
RestAPI -- Stripe : https
RestAPI -- StaticContent : https


' A Client of the application's interactions with the system
node <b>Client</b> <<device>> as Client {
    node <<browser>> as ClientBrowser {
        
    }
}

cloud Infrastructure {
    node Firewall <<DMZ>> {
        collections ComputeEngine as FirewallCE
    }

    frame Intranet {
        node LoadBalancer {
            collections ComputeEngine as LoadBalancerCE
        }

        node RestAPI {
            collections ComputeEngine as RestAPICE
        }

        node WebServer {
            collections ComputeEngine as WebServerCE
        }

        database Database {
            collections ComputeEngine as DatabaseCE
        }
    }
}

frame Cloudflare {
    node DNS {
    }

    node Proxy {
    }
}

' Our authentication provider
node FirebaseAuth {
    node RestAPI as FirebaseRestAPI {

    }
}

' Our banking provider
node Stripe {
    node RestAPI as StripeRestAPI {

    }
}

node StaticContent {
    node Storage {
    }
}


@enduml