// Render this on https://dbdiagram.io

// TODO MAJOR
// - Notifications

// Users
Table User {
    id int [pk, increment]
    name varchar
    email varchar
    phone int
    vat varchar
    type UserType
    createdAt datetime
    updatedAt datetime
    deletedAt datetime
}

Enum UserType {
    "consumer"
    "supplier"
    "admin"
}

// Join table
Table UserAddress {
    userId int [not null, ref: > User.id]
    addressId int [not null, ref: > Address.id]

    Indexes {
        (userId, addressId) [unique]
    }
}

Table Continent {
    id int [pk, increment]
    name varchar
}

Table Country {
    id int [pk, increment]
    continentId int [ref: > Continent.id]
    name varchar
}

Table District {
    id int [pk, increment]
    countryId int [ref: > Country.id]
    name varchar
}

Table City {
    id int [pk, increment]
    districtId int [ref: > District.id]
    name varchar
}

Table County { // Município
    id int [pk, increment]
    cityId int [ref: > City.id]
    name varchar
}

Table Parish { // Freguesia
    id int [pk, increment]
    countyId int [ref: > County.id]
    name varchar
}

Table Street {
    id int [pk, increment]
    parishId int [ref: > Parish.id]
    street varchar
    zipCode varchar
    latitude double // https://enlear.academy/working-with-geo-coordinates-in-mysql-5451e54cddec
    longitude double 
}

Table Address {
    id int [pk, increment]
    streetId int [ref: > Street.id]
    number int
    floor int
    door varchar
}

// Product
Table ProductSpecification {
    id int [pk, increment]
    name varchar
    description varchar
    image varchar
    createdAt datetime
    updatedAt datetime
    deletedAt datetime
}

// Join table
Table ProductSpecificationCategory {
    productSpecificationId int [not null, ref: > ProductSpecification.id]
    categoryId int [not null, ref: > Category.id]

    Indexes {
        (productSpecificationId, categoryId) [unique]
    }
}

Table Category {
    id int [pk, increment]
    name varchar
    parentCategoryId int [ref: > Category.id]
    createdAt datetime
    updatedAt datetime
    deletedAt datetime
}

// Join table
Table CategoryField {
    categoryId int [not null, ref: > Category.id]
    fieldId int [not null, ref: > Field.id]

    Indexes {
        (categoryId, fieldId) [unique]
    }
}

Table Field {
    id int [pk, increment]
    name varchar
    unit varchar
    type FieldType
    createdAt datetime
    updatedAt datetime
    deletedAt datetime
}

Enum FieldType {
    "text"
    "number"
    "date"
    "boolean"
    "enum" // If enum, then the field has a list of possible values, from FieldPossibleValue 
}

Table FieldPossibleValue {
    fieldId int [not null, ref: > Field.id]
    value varchar

    Indexes {
        (fieldId, value) [unique]
    }
}

// The actual ProductSpecification Category Field Value
Table ProductSpecificationFieldValue {
    productSpecificationIdId int [not null, ref: > ProductSpecificationCategory.productSpecificationId]
    fieldId int [not null, ref: > Field.id]
    value varbinary // This is parsed on the backend, depending on the field type

    Indexes {
        (productSpecificationIdId, fieldId) [unique]
    }
}

// TODO Product Discounts?

// A concrete Product from a Supplier
Table Product {
    id int [pk, increment]
    producerId int [not null, ref: > User.id]
    productSpecificationId int [not null, ref: > ProductSpecification.id]
    currentPrice double // when updated, flush it to ProductPricing
    productionDate datetime
    createdAt datetime
    updatedAt datetime
    deletedAt datetime
}

Table ProductPricing {
    id int [pk, increment]
    productId int [pk, ref: > Product.id]
    price double
    createdAt datetime
    updatedAt datetime
    deletedAt datetime
}

// Orders
Table Order {
    id int [pk, increment]
    consumerId int [pk, ref: > User.id]
    totalPrice double [null]
    couponId int [ref: > Coupon.id]
    createdAt datetime
    updatedAt datetime
    deletedAt datetime
}

Table DeliveryStatusUpdate {
    orderId int [pk, ref: > Order.id]
    statusId int [pk, ref: > DeliveryStatus.id]
    locationId int [pk, ref: > Address.id] // TODO should this be it's own thing?
    createdAt datetime
    updatedAt datetime
    deletedAt datetime
}

Table DeliveryStatus {
    id int [pk, increment]
    name varchar
    description varchar
    // Open
    // Processing
    // Delivered
    // ...
    // Closed
}

Table OrderItem {
    orderId int [not null, ref: > Order.id]
    productId int [not null, ref: > Product.id]
    price double // because Product price can change
    quantity int

    Indexes {
        (orderId, productId) [unique]
    }
}

// TODO define rules
// - per customer
// - per supplier
// - per product
// 
// TODO suppliers create coupons?
// -> if so they can only be used in their products

Table Coupon {
    id int [pk, increment]
    code varchar
    discount double
    createdAt datetime
    updatedAt datetime
    deletedAt datetime
}